---
# tasks file for roles/docker_proxy
- name: Run HTTPD
  docker_container:
    name: apache2-server
    image: alexsabri/alexandre:myapache2
    networks:
      - name: app-network
    ports:
     - "80:80"


