name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
# On what action you require that the job is ran
  push:
    branches:
      - master
      - develop
  pull_request:

#job list 
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

     #finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: backend2
        run:  mvn clean verify

  build-push-docker:
    needs: test-backend
    runs-on: ubuntu-22.04

  # steps to perform in job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push backend
      uses: docker/build-push-action@v3
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./backend2
        # Note: tags has to be all lower-case
        tags:  ${{secrets.DOCKERHUB_USERNAME}}/alexandre:mybackend
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/master' }}
    
    - name: Build image and push postgres
      uses: docker/build-push-action@v3  
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./db
        # Note: tags has to be all lower-case
        tags:  ${{secrets.DOCKERHUB_USERNAME}}/alexandre:mypostgres
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/master' }}
    
    - name: Build image and push apache
      uses: docker/build-push-action@v3  
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./http_server
        # Note: tags has to be all lower-case
        tags:  ${{secrets.DOCKERHUB_USERNAME}}/alexandre:myapache2
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/master' }}    
