name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-java@v3
        with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'
      - name: Set up JDK 17
     #finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: backend2
        run:  mvn clean verify
          
